// HOST-ONLY: binds retained owners. It never authenticates, sends, or invokes a writer.
import { open, realpath, lstat, link, unlink, constants } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { exact, identifier, instant, requireThat, sha256 } from './context.mjs';
import { loadApprovalCatalog, validateProposal } from './approvals.mjs';
const HASH=/^[a-f0-9]{64}$/, PROVIDER=/^[A-Za-z0-9_.:@/-]{1,200}$/, MAX_READ=64_000;
function sameCore(a,b,omit=['recorded_at']) { return JSON.stringify(Object.fromEntries(Object.entries(a).filter(([k])=>!omit.includes(k))))===JSON.stringify(Object.fromEntries(Object.entries(b).filter(([k])=>!omit.includes(k)))); }
async function rootChecked(root) {
 const path=resolve(root),leaf=await lstat(path); // Never dereference an untrusted leaf.
 requireThat(leaf.isDirectory()&&!leaf.isSymbolicLink()&&leaf.uid===process.getuid()&&(leaf.mode&0o077)===0,'private_output_directory_required');
 for(let parent=path;;parent=dirname(parent)){try{await lstat(join(parent,'.git'));requireThat(false,'repository_root_forbidden');}catch(error){if(error.code!=='ENOENT')throw error;}if(parent===dirname(parent))break;}
 return await realpath(path);
}
async function secureRead(path) { const parent=await rootChecked(dirname(resolve(path)));requireThat(parent===await realpath(dirname(resolve(path))),'private_output_directory_required');const handle=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const info=await handle.stat();requireThat(info.isFile()&&info.uid===process.getuid()&&(info.mode&0o077)===0&&info.size<=MAX_READ,'private_file_required');return JSON.parse(await handle.readFile('utf8'));}finally{await handle.close();} }
async function publish(path,value,{ignoreRecordedAt=false,equal=null}={}) {
 const temp=path+'.tmp-'+crypto.randomUUID();let handle;
 try {handle=await open(temp,'wx',0o600);await handle.writeFile(JSON.stringify(value));await handle.sync();await handle.close();handle=null;await link(temp,path);await unlink(temp);const directory=await open(dirname(path),'r');try{await directory.sync();}finally{await directory.close();}return {created:true,value};}
 catch(error){if(handle)await handle.close();try{await unlink(temp);}catch{}if(error.code!=='EEXIST')throw error;const prior=await secureRead(path);requireThat(equal?equal(prior,value):ignoreRecordedAt?sameCore(prior,value):sameCore(prior,value,[]),'operation_conflict');return {created:false,value:prior};}
}
function validateApproval(value,p,digest,now){exact(value,['proposal_id','proposal_digest','catalog_digest','decision','revision','expires_at']);requireThat(value.proposal_id===p.proposal_id&&value.proposal_digest===p.digest&&value.catalog_digest===digest&&value.decision==='approve'&&Number.isSafeInteger(value.revision)&&value.revision>0&&instant(value.expires_at)>now,'approval_binding_mismatch');}
export async function validateCurrentDelivery({catalog_env,proposal_id,approval,source_preflight},now=Date.now()) {
 const {catalog,digest}=await loadApprovalCatalog(catalog_env,now);requireThat(catalog?.classification==='executive-reviewed','catalog_changed');identifier(proposal_id);const matches=catalog.proposals.filter(p=>p.proposal_id===proposal_id);requireThat(matches.length===1,'proposal_missing');const proposal=matches[0];validateApproval(approval,proposal,digest,now);return {proposal:structuredClone(proposal),catalog_digest:digest,catalog_expires_at:catalog.expires_at,approval:structuredClone(approval),source_preflight:structuredClone(source_preflight)};
}
export function validateClaudeReadyReceipt(value,proposal,now=Date.now()) {
 exact(value,['kind','sender_account_ref','thread_ref','draft_revision','provider_source_revision','checked_at','expires_at','state']);requireThat(value.kind==='reply'&&value.state==='ready'&&instant(value.checked_at)<=now&&instant(value.expires_at)>now&&instant(value.expires_at)-instant(value.checked_at)<=120000,'source_preflight_invalid');
 requireThat(value.sender_account_ref===proposal.payload.account_ref&&value.thread_ref===proposal.payload.thread_ref&&value.draft_revision===proposal.payload.draft_revision&&value.provider_source_revision===proposal.source_revision,'source_preflight_changed');return structuredClone(value);
}
export async function prepareReplyEnvelope(input,{root,now=Date.now()}) {
 const bound=await validateCurrentDelivery(input,now),p=bound.proposal;requireThat(p.kind==='reply'&&p.executor==='claude-communications','unsupported_action');const preflight=validateClaudeReadyReceipt(bound.source_preflight,p,now);
 const operation_id='reply-'+await sha256({proposal_id:p.proposal_id,proposal_digest:p.digest,catalog_digest:bound.catalog_digest,approval_revision:bound.approval.revision});
 // checked_at proves freshness but is not operation content, so renewed observation stays idempotent.
 const destination_digest=await sha256({source_url:p.source_url,executor:p.executor,payload:p.payload}),expires_at=new Date(Math.min(instant(bound.approval.expires_at),instant(bound.catalog_expires_at))).toISOString();
 const envelope={schema_version:1,kind:'claude-reply-envelope',operation_id,proposal:p,proposal_id:p.proposal_id,proposal_digest:p.digest,catalog_digest:bound.catalog_digest,approval_revision:bound.approval.revision,source_url:p.source_url,executor:p.executor,destination_digest,expires_at,source_preflight:preflight};
 const path=join(await rootChecked(root),operation_id+'.json'),saved=await publish(path,envelope,{equal:(a,b)=>{const x=structuredClone(a),y=structuredClone(b);x.source_preflight.checked_at=y.source_preflight.checked_at=null;return sameCore(x,y,[])}});requireThat(instant(saved.value.source_preflight.expires_at)>now,'source_preflight_expired');return {operation_id,envelope_path:path,expires_at:saved.value.expires_at,idempotent:!saved.created};
}
async function receipt(value,envelope,now,active=true){const keys=['event_id','owner_id','proposal_digest','proposal_id','catalog_digest','approval_revision','revision','attempt_id','supervisor_run_id','executor','state','recorded_at','lease_expires_at','provider_ref','readback_digest','reason_code','source_revision','destination_digest','recorded_via'];exact(value,keys);exact(envelope,['schema_version','kind','operation_id','proposal','proposal_id','proposal_digest','catalog_digest','approval_revision','source_url','executor','destination_digest','expires_at','source_preflight']);await validateProposal(envelope.proposal,instant(envelope.proposal.expires_at)-1);const digest=await sha256({source_url:envelope.proposal.source_url,executor:envelope.proposal.executor,payload:envelope.proposal.payload});requireThat(envelope.proposal.digest===envelope.proposal_digest&&envelope.source_url===envelope.proposal.source_url&&envelope.executor===envelope.proposal.executor&&envelope.destination_digest===digest&&value.state==='dispatch_started'&&HASH.test(value.attempt_id)&&Number.isSafeInteger(value.revision)&&value.revision>0&&value.executor==='claude-communications'&&value.proposal_digest===envelope.proposal_digest&&value.proposal_id===envelope.proposal_id&&value.catalog_digest===envelope.catalog_digest&&value.approval_revision===envelope.approval_revision&&value.source_revision===envelope.source_preflight.provider_source_revision&&value.destination_digest===digest&&instant(value.recorded_at)<=now&&(!active||instant(envelope.expires_at)>now&&instant(value.lease_expires_at)>now),'dispatch_start_invalid');return value;}
export async function issueReplyDispatchPermit({envelope_path,dispatch_start},{now=Date.now()}) { const envelope=await secureRead(envelope_path),start=await receipt(dispatch_start,envelope,now),dispatch_path=envelope_path.replace(/\.json$/,'.dispatch.json');await publish(dispatch_path,start);const expires_at=new Date(Math.min(instant(start.lease_expires_at),instant(envelope.expires_at),instant(envelope.source_preflight.expires_at))).toISOString();requireThat(instant(expires_at)>now,'dispatch_start_invalid');return {schema_version:1,kind:'dispatch-permit',operation_id:envelope.operation_id,proposal_digest:envelope.proposal_digest,attempt_id:start.attempt_id,expires_at,authentication_established:false}; }
export async function recordReplyOutcome({envelope_path,permit,outcome},{now=Date.now()}) {
 exact(permit,['schema_version','kind','operation_id','proposal_digest','attempt_id','expires_at','authentication_established']);exact(outcome,['state','provider_id','readback_digest']);requireThat(permit.schema_version===1&&permit.kind==='dispatch-permit'&&permit.authentication_established===false&&['delivered','unknown'].includes(outcome.state),'outcome_invalid');requireThat(outcome.state==='delivered'?PROVIDER.test(outcome.provider_id??'')&&HASH.test(outcome.readback_digest??''):outcome.provider_id===null&&outcome.readback_digest===null,'outcome_invalid');
 const envelope=await secureRead(envelope_path),start=await secureRead(envelope_path.replace(/\.json$/,'.dispatch.json'));await receipt(start,envelope,now,false);requireThat(envelope.operation_id===permit.operation_id&&envelope.proposal_digest===permit.proposal_digest&&start.attempt_id===permit.attempt_id,'outcome_binding_mismatch');const core={schema_version:1,operation_id:envelope.operation_id,attempt_id:permit.attempt_id,state:outcome.state,provider_id:outcome.provider_id,readback_digest:outcome.readback_digest,retry:outcome.state==='unknown'?'manual-review-required':'not-applicable'},path=envelope_path.replace(/\.json$/,outcome.state==='unknown'?'.outcome-unknown.json':'.outcome-delivered.json');if(outcome.state==='unknown'){try{await secureRead(envelope_path.replace(/\.json$/,'.outcome-delivered.json'));requireThat(false,'terminal_outcome_recorded');}catch(error){if(error.code!=='ENOENT')throw error;}}const saved=await publish(path,{...core,recorded_at:new Date(now).toISOString()},{ignoreRecordedAt:true});return {operation_id:core.operation_id,state:core.state,retry:core.retry,idempotent:!saved.created};
}
export async function mapApprovedAsanaComment(input,now=Date.now()) {
 const bound=await validateCurrentDelivery(input,now),p=bound.proposal;requireThat(p.kind==='asana-change'&&p.executor==='asana-single-writer'&&p.payload.changes.length===1&&p.payload.changes[0].field==='comment','unsupported_action');const v=bound.source_preflight;exact(v,['target','text','target_snapshot','source_ids','content_reviewed','evidence','checked_at','expires_at']);requireThat(/^\d+$/.test(v.target)&&v.target===p.payload.task_gid&&HASH.test(v.target_snapshot)&&v.target_snapshot===p.source_revision&&v.text===p.payload.changes[0].after&&v.content_reviewed===true&&instant(v.checked_at)<=now&&instant(v.expires_at)>now,'source_preflight_changed');requireThat(Array.isArray(v.source_ids)&&v.source_ids.length>0&&v.source_ids.length<=20&&new Set(v.source_ids).size===v.source_ids.length&&v.source_ids.every(x=>HASH.test(x))&&Array.isArray(v.evidence)&&v.evidence.length>0&&v.evidence.length<=20&&v.evidence.every(x=>typeof x==='string'&&x.trim().length>0&&x.length<=10000),'source_evidence_invalid');return {target:v.target,text:v.text,target_snapshot:v.target_snapshot,source_ids:structuredClone(v.source_ids),content_reviewed:true,evidence:structuredClone(v.evidence)};
}
